

#pre defined quran juzes
quran_juzs = {
    "Juz 1": {"first_surah": 1, "last_surah": 2},
    "Juz 2": {"first_surah": 2, "last_surah": 2},
    "Juz 3": {"first_surah": 2, "last_surah": 3},
    "Juz 4": {"first_surah": 3, "last_surah": 4},
    "Juz 5": {"first_surah": 4, "last_surah": 5},
    "Juz 6": {"first_surah": 4, "last_surah": 5},
    "Juz 7": {"first_surah": 5, "last_surah": 6},
    "Juz 8": {"first_surah": 6, "last_surah": 7},
    "Juz 9": {"first_surah": 7, "last_surah": 8},
    "Juz 10": {"first_surah": 8, "last_surah": 9},
    "Juz 11": {"first_surah": 9, "last_surah": 11},
    "Juz 12": {"first_surah": 11, "last_surah": 12},
    "Juz 13": {"first_surah": 12, "last_surah": 14},
    "Juz 14": {"first_surah": 15, "last_surah": 16},
    "Juz 15": {"first_surah": 16, "last_surah": 17},
    "Juz 16": {"first_surah": 17, "last_surah": 18},
    "Juz 17": {"first_surah": 18, "last_surah": 20},
    "Juz 18": {"first_surah": 21, "last_surah": 22},
    "Juz 19": {"first_surah": 23, "last_surah": 25},
    "Juz 20": {"first_surah": 25, "last_surah": 27},
    "Juz 21": {"first_surah": 27, "last_surah": 29},
    "Juz 22": {"first_surah": 29, "last_surah": 32},
    "Juz 23": {"first_surah": 33, "last_surah": 36},
    "Juz 24": {"first_surah": 36, "last_surah": 39},
    "Juz 25": {"first_surah": 40, "last_surah": 44},
    "Juz 26": {"first_surah": 45, "last_surah": 51},
    "Juz 27": {"first_surah": 51, "last_surah": 57},
    "Juz 28": {"first_surah": 58, "last_surah": 66},
    "Juz 29": {"first_surah": 67, "last_surah": 77},
    "Juz 30": {"first_surah": 78, "last_surah": 114},
}
